-- CONNECTION: url=jdbc:oracle:thin:@//localhost:1521/XE




-- New script in localhost.
-- Connection Type: dev 
-- Url: jdbc:oracle:thin:@//localhost:1521/XE
-- workspace : C:\workspace\multi\03_DB
-- Date: 2024. 5. 12.
-- Time: 오후 6:22:03

CREATE USER MINI IDENTIFIED BY mini;
GRANT CONNECT, RESOURCE, DBA TO MINI;

-- TABLE 생성

CREATE TABLE MEMBERS(
    MEMBER_NUM VARCHAR2(100)  PRIMARY KEY,
    ID VARCHAR2(100) UNIQUE, -- NOT NULL-> UNIQUE 변경
    PW VARCHAR2(100) NOT NULL,
    NAME VARCHAR2(100),
    EMAIL_ID VARCHAR2(100),
    EMAIL_SITE VARCHAR2(100),   -- 추가!
    ADMIN NUMBER
    );

--DROP TABLE MEMBERS ;

CREATE TABLE CARS(
	CAR_NUM VARCHAR2(100) PRIMARY KEY,
	CAR_NAME VARCHAR2(100) NOT NULL,
	CAR_CATEGORY VARCHAR2(100) NOT NULL,
	CAR_FEATURE VARCHAR2(100) NOT NULL,
	CAR_PREF_COMFORT NUMBER NOT NULL,
	CAR_PREF_WEIGHT NUMBER NOT NULL,
	CAR_PREF_PASSENGER NUMBER NOT NULL
--	(SELECT REVIEW_NUM FROM REVIEWS WHERE  )AS 별점 총합/리뷰개수 추가하기!
	);

CREATE TABLE PRODUCTS(
	PRODUCT_NUM VARCHAR2(100) PRIMARY KEY,
	CAR_NUM VARCHAR2(100) REFERENCES CARS(CAR_NUM),
	PRODUCT_STATUS VARCHAR2(100),
	PRODUCT_PRICE NUMBER NOT NULL,
	PRODUCT_AVAILABLE NUMBER NOT NULL
	);

CREATE TABLE ORDERS(
	ORDER_NUM VARCHAR2(100) PRIMARY KEY,
	MEMBER_NUM VARCHAR2(100) REFERENCES MEMBERS(MEMBER_NUM),
	--CAR_NUM VARCHAR2(100) REFERENCES CARS(CAR_NUM), // 차량번호(X) 차량고유번호PRODUCT_NUM 요게 맞습니다! 아랫줄은 수정내
	PRODUCT_NUM VARCHAR2(100) REFERENCES PRODUCTS(PRODUCT_NUM),
	ORDER_STATUS NUMBER NOT NULL,
	ORDER_REFUND_REQUEST NUMBER NOT NULL,
	ORDER_REFUND_COMPLETE NUMBER NOT NULL
	);

CREATE TABLE REVIEWS(
    REVIEW_NUM VARCHAR2(100) PRIMARY KEY,
    ORDER_NUM VARCHAR2(100) REFERENCES ORDERS(ORDER_NUM),
    RATING NUMBER NOT NULL,
    TITLE VARCHAR2(100) NOT NULL,
    CONTENTS VARCHAR2(1000) NOT NULL
    );
   

CREATE TABLE PRESETS(
	PRESET_NUM VARCHAR2(100) PRIMARY KEY,
	MEMBER_NUM VARCHAR2(100) REFERENCES MEMBERS(MEMBER_NUM),
	PRESET_COMFORT NUMBER NOT NULL,
	PRESET_WEIGHT NUMBER NOT NULL,
	PRESET_PASSENGER NUMBER NOT NULL
	);


-- SEQUENCE 생성

CREATE SEQUENCE MEMBER_NUM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE SEQUENCE REVIEW_NUM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE SEQUENCE CAR_NUM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE SEQUENCE PRODUCT_NUM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


CREATE SEQUENCE PRESET_NUM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;

CREATE SEQUENCE ORDER_NUM_SEQ
START WITH 1
INCREMENT BY 1
NOMAXVALUE
NOCYCLE
NOCACHE;


=======
SELECT * FROM PRODUCTS;
SELECT * FROM ORDERS;
SELECT * FROM CARS;
SELECT * FROM MEMBERS;


INSERT INTO MEMBERS values ('M'||MEMBER_NUM_SEQ.NEXTVAL,'admin','admin','관리자','admin','@gmail.com',1);
INSERT INTO MEMBERS values ('M'||MEMBER_NUM_SEQ.NEXTVAL,'1','1','1','1','@1',0);



INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Genesis GV80', '대형SUV','굉장히 많은 짐을 적재하고도 넓은 뒷좌석 보유', 1,1,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'KIA K7', '대형','넓은 적재량과 편안한 뒷좌석', 1,1,0);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Genesis G80', '대형','뒷좌석에 손님을 모시기 좋다', 1,0,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Genesis G70', '준중형','뒷좌석은 좁지만 훌륭한 주행감', 1,0,0);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Hyundai 투싼', '중형SUV','무난한 승차감과 준수한 적재량', 0,1,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'KIA 레이', '미니밴','소형이지만 넓은 적재공간 보유', 0,1,0);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'KIA 셀토스', '소형SUV','렌트 SUV의 대명사', 0,0,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Hyundai 아반떼', '준중형','무난함의 표본', 0,0,0);
=======
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Genesis GV80', '준중형차','편안', 1,1,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'KIA K7', '준중형차','편안', 1,1,0);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Genesis G80', '준중형차','편안', 1,0,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Genesis G70', '준중형차','편안', 1,0,0);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Hyundai 투싼', '준중형차','편안', 0,1,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'KIA 레이', '준중형차','편안', 0,1,0);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'KIA 셀토스', '준중형차','편안', 0,0,1);
INSERT INTO CARS VALUES('C'||CAR_NUM_SEQ.NEXTVAL, 'Hyundai 아반떼', '준중형차','편안', 0,0,0);

INSERT INTO PRODUCTS VALUES ('P'||PRODUCT_NUM_SEQ.NEXTVAL, 'C1', 1, 5000, 4);
INSERT INTO ORDERS VALUES ('O'||ORDER_NUM_SEQ.NEXTVAL, 'M2', 'P1',1,1,1);
--INSERT INTO REVIEWS values (REVIEW_NUM_SEQ.NEXTVAL,'O2',3 ,'A','ABC');



-- DROP TABLE CARS;
COMMIT;

SELECT * FROM MEMBERS;



=======
CREATE OR REPLACE VIEW V_REVIEW_TABLE
( REVIEW_NUM , TITLE, CAR_NUM, WRITER, ORDER_NUM, RATING, CONTENTS)
AS
SELECT 
    B.REVIEW_NUM,
    B.TITLE,
    C.CAR_NUM,
    D.ID,
    A.ORDER_NUM,
    B.RATING,
    B.CONTENTS
FROM ORDERS A    
LEFT JOIN REVIEWS B ON A.ORDER_NUM = B.ORDER_NUM 
LEFT JOIN PRODUCTS C ON A.PRODUCT_NUM = C.PRODUCT_NUM
LEFT JOIN MEMBERS D ON A.MEMBER_NUM = D.MEMBER_NUM;
--

INSERT INTO REVIEWS VALUES (''||REVIEW_NUM_SEQ.NEXTVAL, 'O2', 3, '후기','내용');
INSERT INTO PRODUCTS VALUES ('P'||PRODUCT_NUM_SEQ.NEXTVAL, 'C2', 1, 5000, 4);
INSERT INTO ORDERS VALUES ('O'||ORDER_NUM_SEQ.NEXTVAL, 'M2', 'P2',1,1,1);
INSERT INTO REVIEWS VALUES (''||REVIEW_NUM_SEQ.NEXTVAL, 'O4', 2, '후기1','내용1');



DROP TABLE PRESETS;
DROP TABLE REVIEWS;
DROP TABLE ORDERS;
DROP TABLE PRODUCTS;
DROP TABLE CARS;
DROP TABLE MEMBERS;


DROP SEQUENCE MEMBER_NUM_SEQ;
DROP SEQUENCE CAR_NUM_SEQ;
DROP SEQUENCE PRODUCT_NUM_SEQ;
DROP SEQUENCE ORDER_NUM_SEQ;
DROP SEQUENCE REVIEW_NUM_SEQ;
DROP SEQUENCE PRESET_NUM_SEQ;


SELECT * FROM  V_REVIEW_TABLE WHERE REVIEW_NUM IS NOT NULL AND WRITER = '1';


INSERT INTO ORDERS VALUES ('O'||ORDER_NUM_SEQ.NEXTVAL, 'M2', 'P2',1,1,1);
INSERT INTO ORDERS VALUES ('O'||ORDER_NUM_SEQ.NEXTVAL, 'M2', 'P1',1,1,1);






